import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class Level5 here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class Level5 extends World
{

    /**
     * Constructor for objects of class Level5.
     * 
     */
    public Level5()
    {    
        // Create a new world with 600x400 cells with a cell size of 1x1 pixels.
        super(70, 40, 15); 
        prepare();
    }
    
    /**
     * Prepare the world for the start of the program.
     * That is: create the initial objects and add them to the world.
     */
    private void prepare()
    {
        MazeBlock mazeBlock = new MazeBlock();
        addObject(mazeBlock,68,35);
        MazeBlock mazeBlock2 = new MazeBlock();
        addObject(mazeBlock2,65,35);
        MazeBlock mazeBlock3 = new MazeBlock();
        addObject(mazeBlock3,62,35);
        MazeBlock mazeBlock4 = new MazeBlock();
        addObject(mazeBlock4,59,35);
        MazeBlock mazeBlock5 = new MazeBlock();
        addObject(mazeBlock5,51,35);
        MazeBlock mazeBlock6 = new MazeBlock();
        addObject(mazeBlock6,51,32);
        MazeBlock mazeBlock7 = new MazeBlock();
        addObject(mazeBlock7,48,35);
        MazeBlock mazeBlock8 = new MazeBlock();
        addObject(mazeBlock8,59,29);
        MazeBlock mazeBlock9 = new MazeBlock();
        addObject(mazeBlock9,59,26);
        MazeBlock mazeBlock10 = new MazeBlock();
        addObject(mazeBlock10,56,26);
        MazeBlock mazeBlock11 = new MazeBlock();
        addObject(mazeBlock11,65,26);
        MazeBlock mazeBlock12 = new MazeBlock();
        addObject(mazeBlock12,65,29);
        MazeBlock mazeBlock13 = new MazeBlock();
        addObject(mazeBlock13,65,23);
        MazeBlock mazeBlock14 = new MazeBlock();
        addObject(mazeBlock14,68,17);
        MazeBlock mazeBlock15 = new MazeBlock();
        addObject(mazeBlock15,65,17);
        MazeBlock mazeBlock16 = new MazeBlock();
        addObject(mazeBlock16,61,17);
        mazeBlock16.setLocation(62,17);
        MazeBlock mazeBlock17 = new MazeBlock();
        addObject(mazeBlock17,59,17);
        mazeBlock5.setLocation(52,35);
        mazeBlock6.setLocation(53,32);
        mazeBlock5.setLocation(52,34);
        mazeBlock6.setLocation(53,32);
        mazeBlock6.setLocation(52,32);
        mazeBlock5.setLocation(53,34);
        mazeBlock5.setLocation(53,35);
        mazeBlock6.setLocation(53,32);
        mazeBlock7.setLocation(49,34);
        mazeBlock7.setLocation(50,35);
        mazeBlock17.setLocation(58,21);
        mazeBlock17.setLocation(56,20);
        MazeBlock mazeBlock18 = new MazeBlock();
        addObject(mazeBlock18,43,35);
        MazeBlock mazeBlock19 = new MazeBlock();
        addObject(mazeBlock19,43,38);
        MazeBlock mazeBlock20 = new MazeBlock();
        addObject(mazeBlock20,43,32);
        MazeBlock mazeBlock21 = new MazeBlock();
        addObject(mazeBlock21,49,26);
        MazeBlock mazeBlock22 = new MazeBlock();
        addObject(mazeBlock22,46,26);
        MazeBlock mazeBlock23 = new MazeBlock();
        addObject(mazeBlock23,46,23);
        MazeBlock mazeBlock24 = new MazeBlock();
        addObject(mazeBlock24,46,17);
        MazeBlock mazeBlock25 = new MazeBlock();
        addObject(mazeBlock25,43,17);
        MazeBlock mazeBlock26 = new MazeBlock();
        addObject(mazeBlock26,40,17);
        MazeBlock mazeBlock27 = new MazeBlock();
        addObject(mazeBlock27,40,14);
        MazeBlock mazeBlock28 = new MazeBlock();
        addObject(mazeBlock28,40,23);
        MazeBlock mazeBlock29 = new MazeBlock();
        addObject(mazeBlock29,36,23);
        mazeBlock29.setLocation(37,23);
        MazeBlock mazeBlock30 = new MazeBlock();
        addObject(mazeBlock30,34,23);
        MazeBlock mazeBlock31 = new MazeBlock();
        addObject(mazeBlock31,34,28);
        mazeBlock31.setLocation(34,29);
        MazeBlock mazeBlock32 = new MazeBlock();
        addObject(mazeBlock32,37,29);
        MazeBlock mazeBlock33 = new MazeBlock();
        addObject(mazeBlock33,34,32);
        MazeBlock mazeBlock34 = new MazeBlock();
        addObject(mazeBlock34,37,38);
        mazeBlock4.setLocation(57,35);
        mazeBlock4.setLocation(56,36);
        mazeBlock4.setLocation(56,35);
        MazeBlock mazeBlock35 = new MazeBlock();
        addObject(mazeBlock35,27,29);
        mazeBlock35.setLocation(28,30);
        mazeBlock35.setLocation(28,29);
        MazeBlock mazeBlock36 = new MazeBlock();
        addObject(mazeBlock36,28,32);
        MazeBlock mazeBlock37 = new MazeBlock();
        addObject(mazeBlock37,25,32);
        MazeBlock mazeBlock38 = new MazeBlock();
        addObject(mazeBlock38,28,35);
        mazeBlock34.setLocation(34,38);
        MazeBlock mazeBlock39 = new MazeBlock();
        addObject(mazeBlock39,52,14);
        mazeBlock39.setLocation(52,14);
        mazeBlock39.setLocation(53,14);
        MazeBlock mazeBlock40 = new MazeBlock();
        addObject(mazeBlock40,53,11);
        MazeBlock mazeBlock41 = new MazeBlock();
        addObject(mazeBlock41,50,11);
        MazeBlock mazeBlock42 = new MazeBlock();
        addObject(mazeBlock42,56,11);
        MazeBlock mazeBlock43 = new MazeBlock();
        addObject(mazeBlock43,21,38);
        MazeBlock mazeBlock44 = new MazeBlock();
        addObject(mazeBlock44,15,35);
        MazeBlock mazeBlock45 = new MazeBlock();
        addObject(mazeBlock45,15,32);
        MazeBlock mazeBlock46 = new MazeBlock();
        addObject(mazeBlock46,18,32);
        MazeBlock mazeBlock47 = new MazeBlock();
        addObject(mazeBlock47,16,24);
        MazeBlock mazeBlock48 = new MazeBlock();
        addObject(mazeBlock48,19,24);
        MazeBlock mazeBlock49 = new MazeBlock();
        addObject(mazeBlock49,22,24);
        mazeBlock49.setLocation(22,25);
        mazeBlock48.setLocation(19,25);
        mazeBlock47.setLocation(16,25);
        mazeBlock49.setLocation(23,26);
        mazeBlock49.setLocation(22,26);
        mazeBlock48.setLocation(20,26);
        mazeBlock47.setLocation(16,26);
        mazeBlock48.setLocation(19,26);
        MazeBlock mazeBlock50 = new MazeBlock();
        addObject(mazeBlock50,19,15);
        MazeBlock mazeBlock51 = new MazeBlock();
        addObject(mazeBlock51,19,18);
        MazeBlock mazeBlock52 = new MazeBlock();
        addObject(mazeBlock52,19,12);
        mazeBlock50.setLocation(19,19);
        mazeBlock51.setLocation(19,19);
        mazeBlock51.setLocation(19,19);
        mazeBlock51.setLocation(19,20);
        mazeBlock50.setLocation(19,17);
        mazeBlock52.setLocation(20,15);
        mazeBlock52.setLocation(19,14);
        MazeBlock mazeBlock53 = new MazeBlock();
        addObject(mazeBlock53,22,17);
        MazeBlock mazeBlock54 = new MazeBlock();
        addObject(mazeBlock54,28,17);
        MazeBlock mazeBlock55 = new MazeBlock();
        addObject(mazeBlock55,28,14);
        MazeBlock mazeBlock56 = new MazeBlock();
        addObject(mazeBlock56,28,20);
        MazeBlock mazeBlock57 = new MazeBlock();
        addObject(mazeBlock57,34,14);
        MazeBlock mazeBlock58 = new MazeBlock();
        addObject(mazeBlock58,34,11);
        MazeBlock mazeBlock59 = new MazeBlock();
        addObject(mazeBlock59,34,7);
        mazeBlock59.setLocation(35,8);
        mazeBlock59.setLocation(35,8);
        mazeBlock59.setLocation(35,8);
        mazeBlock59.setLocation(34,8);
        MazeBlock mazeBlock60 = new MazeBlock();
        addObject(mazeBlock60,37,8);
        MazeBlock mazeBlock61 = new MazeBlock();
        addObject(mazeBlock61,30,8);
        mazeBlock61.setLocation(32,8);
        mazeBlock61.setLocation(31,8);
        MazeBlock mazeBlock62 = new MazeBlock();
        addObject(mazeBlock62,34,5);
        MazeBlock mazeBlock63 = new MazeBlock();
        addObject(mazeBlock63,41,1);
        MazeBlock mazeBlock64 = new MazeBlock();
        addObject(mazeBlock64,44,1);
        MazeBlock mazeBlock65 = new MazeBlock();
        addObject(mazeBlock65,44,4);
        MazeBlock mazeBlock66 = new MazeBlock();
        addObject(mazeBlock66,44,9);
        mazeBlock66.setLocation(14,1);
        MazeBlock mazeBlock67 = new MazeBlock();
        addObject(mazeBlock67,14,4);
        MazeBlock mazeBlock68 = new MazeBlock();
        addObject(mazeBlock68,17,4);
        MazeBlock mazeBlock69 = new MazeBlock();
        addObject(mazeBlock69,6,7);
        MazeBlock mazeBlock70 = new MazeBlock();
        addObject(mazeBlock70,6,10);
        MazeBlock mazeBlock71 = new MazeBlock();
        addObject(mazeBlock71,9,10);
        MazeBlock mazeBlock72 = new MazeBlock();
        addObject(mazeBlock72,3,10);
        MazeBlock mazeBlock73 = new MazeBlock();
        addObject(mazeBlock73,4,16);
        MazeBlock mazeBlock74 = new MazeBlock();
        addObject(mazeBlock74,7,16);
        MazeBlock mazeBlock75 = new MazeBlock();
        addObject(mazeBlock75,7,19);
        MazeBlock mazeBlock76 = new MazeBlock();
        addObject(mazeBlock76,13,17);
        MazeBlock mazeBlock77 = new MazeBlock();
        addObject(mazeBlock77,25,1);
        MazeBlock mazeBlock78 = new MazeBlock();
        addObject(mazeBlock78,25,4);
        MazeBlock mazeBlock79 = new MazeBlock();
        addObject(mazeBlock79,25,7);
        MazeBlock mazeBlock80 = new MazeBlock();
        addObject(mazeBlock80,1,27);
        MazeBlock mazeBlock81 = new MazeBlock();
        addObject(mazeBlock81,4,27);
        MazeBlock mazeBlock82 = new MazeBlock();
        addObject(mazeBlock82,4,30);
        MazeBlock mazeBlock83 = new MazeBlock();
        addObject(mazeBlock83,10,28);
        mazeBlock83.setLocation(6,36);
        MazeBlock mazeBlock84 = new MazeBlock();
        addObject(mazeBlock84,10,26);
        MazeBlock mazeBlock85 = new MazeBlock();
        addObject(mazeBlock85,51,1);
        MazeBlock mazeBlock86 = new MazeBlock();
        addObject(mazeBlock86,51,4);
        MazeBlock mazeBlock87 = new MazeBlock();
        addObject(mazeBlock87,54,4);
        MazeBlock mazeBlock88 = new MazeBlock();
        addObject(mazeBlock88,60,1);
        MazeBlock mazeBlock89 = new MazeBlock();
        addObject(mazeBlock89,60,4);
        MazeBlock mazeBlock90 = new MazeBlock();
        addObject(mazeBlock90,64,4);
        mazeBlock90.setLocation(63,4);
        MazeBlock mazeBlock91 = new MazeBlock();
        addObject(mazeBlock91,63,9);
        MazeBlock mazeBlock92 = new MazeBlock();
        addObject(mazeBlock92,63,12);
        mazeBlock92.setLocation(68,10);
        mazeBlock91.setLocation(61,7);
        mazeBlock91.setLocation(60,7);
        MazeBlock mazeBlock93 = new MazeBlock();
        addObject(mazeBlock93,60,10);
        mazeBlock93.setLocation(64,10);
        mazeBlock93.setLocation(65,10);
        mazeBlock93.setLocation(45,9);
        mazeBlock93.setLocation(45,9);
        mazeBlock93.setLocation(44,9);
        mazeBlock92.setLocation(65,10);
        mazeBlock92.setLocation(65,11);
        Spike spike = new Spike();
        addObject(spike,43,30);
        Spike spike2 = new Spike();
        addObject(spike2,38,39);
        Spike spike3 = new Spike();
        addObject(spike3,10,39);
        Spike spike4 = new Spike();
        addObject(spike4,4,25);
        Spike spike5 = new Spike();
        addObject(spike5,13,15);
        Spike spike6 = new Spike();
        addObject(spike6,19,12);
        Spike spike7 = new Spike();
        addObject(spike7,34,3);
        Spike spike8 = new Spike();
        addObject(spike8,65,9);
        spike4 spike42 = new spike4();
        addObject(spike42,32,23);
        spike2 spike22 = new spike2();
        addObject(spike22,30,17);
        spike2 spike23 = new spike2();
        addObject(spike23,45,38);
        spike2 spike24 = new spike2();
        addObject(spike24,51,26);
        spike2 spike25 = new spike2();
        addObject(spike25,48,17);
        spike3 spike32 = new spike3();
        addObject(spike32,44,11);
        spike2 spike26 = new spike2();
        addObject(spike26,27,1);
        Spike spike9 = new Spike();
        addObject(spike9,28,12);
        spike2 spike27 = new spike2();
        addObject(spike27,11,10);
        spike2 spike28 = new spike2();
        addObject(spike28,24,26);
        spike3 spike33 = new spike3();
        addObject(spike33,22,19);
        spike2 spike29 = new spike2();
        addObject(spike29,0,22);
        spike2 spike210 = new spike2();
        addObject(spike210,0,13);
        spike3 spike34 = new spike3();
        addObject(spike34,16,6);
        Player player = new Player();
        addObject(player,66,38);
        Gate gate = new Gate();
        addObject(gate,68,3);
        Key key = new Key();
        addObject(key,3,2);
        mazeBlock92.setLocation(66,11);
        spike8.setLocation(66,9);
        spike2 spike211 = new spike2();
        addObject(spike211,58,11);
        spike2 spike212 = new spike2();
        addObject(spike212,48,23);
        removeObject(spike);
        mazeBlock59.setLocation(33,8);
        Timer timer = new Timer(60);
        addObject(timer,33,8);
        mazeBlock61.setLocation(34,8);
        mazeBlock59.setLocation(34,8);
        mazeBlock59.setLocation(34,8);
        mazeBlock59.setLocation(35,8);
        timer.setLocation(35,8);
        LuckyBox luckyBox = new LuckyBox();
        addObject(luckyBox,54,1);
        luckyBox.setLocation(54,1);
        mazeBlock59.setLocation(34,8);
        mazeBlock17.setLocation(53,20);
        Laser laser = new Laser();
        addObject(laser,62,26);
        laser.setLocation(62,27);
        Laser laser2 = new Laser();
        addObject(laser2,62,27);
        laser.setLocation(62,25);
        Laser laser3 = new Laser();
        addObject(laser3,62,25);
        laser.setLocation(62,26);
        Laser laser4 = new Laser();
        addObject(laser4,62,26);
        Laser laser5 = new Laser();
        addObject(laser5,59,34);
        laser5.setLocation(59,35);
        Laser laser6 = new Laser();
        addObject(laser6,59,35);
        laser5.setLocation(59,36);
        Laser laser7 = new Laser();
        addObject(laser7,59,36);
        laser5.setLocation(60,36);
        removeObject(laser7);
        removeObject(laser6);
        removeObject(laser5);
        addObject(laser5,59,35);
        removeObject(laser5);
        Laser laser8 = new Laser();
        addObject(laser8,59,34);
        laser8.setLocation(59,35);
        Laser laser9 = new Laser();
        addObject(laser9,59,35);
        laser8.setLocation(59,36);
        Laser laser10 = new Laser();
        addObject(laser10,59,36);
        laser8.setLocation(59,34);
        Laser laser11 = new Laser();
        addObject(laser11,59,34);
        Laser laser12 = new Laser();
        addObject(laser12,25,18);
        laser12.setLocation(25,17);
        Laser laser13 = new Laser();
        addObject(laser13,25,17);
        laser12.setLocation(25,18);
        Laser laser14 = new Laser();
        addObject(laser14,25,18);
        laser12.setLocation(25,16);
        Laser laser15 = new Laser();
        addObject(laser15,25,16);
        Laser laser16 = new Laser();
        addObject(laser16,16,18);
        laser16.setLocation(16,17);
        Laser laser17 = new Laser();
        addObject(laser17,16,17);
        laser16.setLocation(16,18);
        Laser laser18 = new Laser();
        addObject(laser18,16,18);
        laser17.setLocation(16,16);
        Laser laser19 = new Laser();
        addObject(laser19,16,16);
        laser16.setLocation(16,17);
        Laser laser20 = new Laser();
        addObject(laser20,16,17);
        LaserVertical laserVertical = new LaserVertical();
        addObject(laserVertical,66,14);
        laserVertical.setLocation(65,14);
        LaserVertical laserVertical2 = new LaserVertical();
        addObject(laserVertical2,65,14);
        laserVertical.setLocation(66,14);
        LaserVertical laserVertical3 = new LaserVertical();
        addObject(laserVertical3,66,14);
        laserVertical.setLocation(67,14);
        LaserVertical laserVertical4 = new LaserVertical();
        addObject(laserVertical4,67,14);
        Laser laser21 = new Laser();
        addObject(laser21,57,4);
        laser21.setLocation(57,5);
        Laser laser22 = new Laser();
        addObject(laser22,57,5);
        laser21.setLocation(57,4);
        Laser laser23 = new Laser();
        addObject(laser23,57,4);
        laser21.setLocation(57,3);
        Laser laser24 = new Laser();
        addObject(laser24,57,3);
        Laser laser25 = new Laser();
        addObject(laser25,43,23);
        laser25.setLocation(43,22);
        Laser laser26 = new Laser();
        addObject(laser26,43,22);
        laser25.setLocation(43,23);
        Laser laser27 = new Laser();
        addObject(laser27,43,23);
        laser25.setLocation(43,24);
        Laser laser28 = new Laser();
        addObject(laser28,43,24);
        luckyBox.setLocation(60,38);
        luckyBox.setLocation(55,2);
    }
}
