import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class level4 here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class Level4 extends World
{

    /**
     * Constructor for objects of class level4.
     * 
     */
    public Level4()
    {    
        // Create a new world with 600x400 cells with a cell size of 1x1 pixels.
        super(70, 40, 15);
        prepare();
    }
    
    /**
     * Prepare the world for the start of the program.
     * That is: create the initial objects and add them to the world.
     */
    private void prepare()
    {
        MazeBlock mazeBlock = new MazeBlock();
        addObject(mazeBlock,68,38);
        MazeBlock mazeBlock2 = new MazeBlock();
        addObject(mazeBlock2,65,38);
        MazeBlock mazeBlock3 = new MazeBlock();
        addObject(mazeBlock3,62,38);
        MazeBlock mazeBlock4 = new MazeBlock();
        addObject(mazeBlock4,59,38);
        MazeBlock mazeBlock5 = new MazeBlock();
        addObject(mazeBlock5,68,31);
        MazeBlock mazeBlock6 = new MazeBlock();
        addObject(mazeBlock6,68,28);
        MazeBlock mazeBlock7 = new MazeBlock();
        addObject(mazeBlock7,68,25);
        MazeBlock mazeBlock8 = new MazeBlock();
        addObject(mazeBlock8,29,1);
        MazeBlock mazeBlock9 = new MazeBlock();
        addObject(mazeBlock9,29,4);
        MazeBlock mazeBlock10 = new MazeBlock();
        addObject(mazeBlock10,29,7);
        MazeBlock mazeBlock11 = new MazeBlock();
        addObject(mazeBlock11,29,10);
        MazeBlock mazeBlock12 = new MazeBlock();
        addObject(mazeBlock12,29,13);
        MazeBlock mazeBlock13 = new MazeBlock();
        addObject(mazeBlock13,29,16);
        MazeBlock mazeBlock14 = new MazeBlock();
        addObject(mazeBlock14,29,19);
        MazeBlock mazeBlock15 = new MazeBlock();
        addObject(mazeBlock15,29,22);
        MazeBlock mazeBlock16 = new MazeBlock();
        addObject(mazeBlock16,29,25);
        MazeBlock mazeBlock17 = new MazeBlock();
        addObject(mazeBlock17,29,28);
        MazeBlock mazeBlock18 = new MazeBlock();
        addObject(mazeBlock18,29,31);
        MazeBlock mazeBlock19 = new MazeBlock();
        addObject(mazeBlock19,32,31);
        MazeBlock mazeBlock20 = new MazeBlock();
        addObject(mazeBlock20,35,31);
        MazeBlock mazeBlock21 = new MazeBlock();
        addObject(mazeBlock21,38,31);
        MazeBlock mazeBlock22 = new MazeBlock();
        addObject(mazeBlock22,42,31);
        mazeBlock22.setLocation(42,31);
        mazeBlock22.setLocation(41,31);
        MazeBlock mazeBlock23 = new MazeBlock();
        addObject(mazeBlock23,44,31);
        MazeBlock mazeBlock24 = new MazeBlock();
        addObject(mazeBlock24,47,31);
        MazeBlock mazeBlock25 = new MazeBlock();
        addObject(mazeBlock25,32,25);
        MazeBlock mazeBlock26 = new MazeBlock();
        addObject(mazeBlock26,35,25);
        MazeBlock mazeBlock27 = new MazeBlock();
        addObject(mazeBlock27,38,25);
        MazeBlock mazeBlock28 = new MazeBlock();
        addObject(mazeBlock28,41,25);
        MazeBlock mazeBlock29 = new MazeBlock();
        addObject(mazeBlock29,44,25);
        MazeBlock mazeBlock30 = new MazeBlock();
        addObject(mazeBlock30,44,21);
        removeObject(mazeBlock30);
        MazeBlock MazeBlock30 = new MazeBlock();
        addObject(mazeBlock30,50,31);
        MazeBlock mazeBlock31 = new MazeBlock();
        addObject(mazeBlock31,50,28);
        MazeBlock mazeBlock32 = new MazeBlock();
        addObject(mazeBlock32,50,25);
        MazeBlock mazeBlock33 = new MazeBlock();
        addObject(mazeBlock33,50,22);
        MazeBlock mazeBlock34 = new MazeBlock();
        addObject(mazeBlock34,50,19);
        MazeBlock mazeBlock35 = new MazeBlock();
        addObject(mazeBlock35,50,16);
        MazeBlock mazeBlock36 = new MazeBlock();
        addObject(mazeBlock36,47,19);
        MazeBlock mazeBlock37 = new MazeBlock();
        addObject(mazeBlock37,44,19);
        MazeBlock mazeBlock38 = new MazeBlock();
        addObject(mazeBlock38,41,19);
        MazeBlock mazeBlock39 = new MazeBlock();
        addObject(mazeBlock39,38,19);
        MazeBlock mazeBlock40 = new MazeBlock();
        addObject(mazeBlock40,35,19);
        MazeBlock mazeBlock41 = new MazeBlock();
        addObject(mazeBlock41,50,13);
        MazeBlock mazeBlock42 = new MazeBlock();
        addObject(mazeBlock42,50,10);
        MazeBlock mazeBlock43 = new MazeBlock();
        addObject(mazeBlock43,50,6);
        mazeBlock43.setLocation(50,7);
        MazeBlock mazeBlock44 = new MazeBlock();
        addObject(mazeBlock44,32,13);
        MazeBlock mazeBlock45 = new MazeBlock();
        addObject(mazeBlock45,35,13);
        MazeBlock mazeBlock46 = new MazeBlock();
        addObject(mazeBlock46,38,13);
        MazeBlock mazeBlock47 = new MazeBlock();
        addObject(mazeBlock47,41,13);
        MazeBlock mazeBlock48 = new MazeBlock();
        addObject(mazeBlock48,44,13);
        MazeBlock mazeBlock49 = new MazeBlock();
        addObject(mazeBlock49,32,4);
        MazeBlock mazeBlock50 = new MazeBlock();
        addObject(mazeBlock50,36,4);
        mazeBlock50.setLocation(36,4);
        mazeBlock50.setLocation(35,4);
        MazeBlock mazeBlock51 = new MazeBlock();
        addObject(mazeBlock51,41,10);
        MazeBlock mazeBlock52 = new MazeBlock();
        addObject(mazeBlock52,38,4);
        MazeBlock mazeBlock53 = new MazeBlock();
        addObject(mazeBlock53,41,4);
        MazeBlock mazeBlock54 = new MazeBlock();
        addObject(mazeBlock54,56,1);
        MazeBlock mazeBlock55 = new MazeBlock();
        addObject(mazeBlock55,56,4);
        removeObject(mazeBlock55);
        removeObject(mazeBlock54);
        MazeBlock MazeBlock54 = new MazeBlock();
        addObject(mazeBlock54,59,1);
        MazeBlock MazeBlock55 = new MazeBlock();
        addObject(mazeBlock55,59,4);
        MazeBlock mazeBlock56 = new MazeBlock();
        addObject(mazeBlock56,59,7);
        MazeBlock mazeBlock57 = new MazeBlock();
        addObject(mazeBlock57,59,10);
        MazeBlock mazeBlock58 = new MazeBlock();
        addObject(mazeBlock58,62,10);
        MazeBlock mazeBlock59 = new MazeBlock();
        addObject(mazeBlock59,63,13);
        mazeBlock59.setLocation(63,14);
        mazeBlock59.setLocation(62,13);
        MazeBlock mazeBlock60 = new MazeBlock();
        addObject(mazeBlock60,62,16);
        removeObject(mazeBlock57);
        removeObject(mazeBlock58);
        removeObject(mazeBlock59);
        removeObject(mazeBlock60);
        MazeBlock MazeBlock57 = new MazeBlock();
        addObject(mazeBlock57,62,7);
        MazeBlock MazeBlock58 = new MazeBlock();
        addObject(mazeBlock58,65,7);
        MazeBlock MazeBlock59 = new MazeBlock();
        addObject(mazeBlock59,65,10);
        MazeBlock MazeBlock60 = new MazeBlock();
        addObject(mazeBlock60,65,13);
        MazeBlock mazeBlock61 = new MazeBlock();
        addObject(mazeBlock61,68,19);
        MazeBlock mazeBlock62 = new MazeBlock();
        addObject(mazeBlock62,65,19);
        MazeBlock mazeBlock63 = new MazeBlock();
        addObject(mazeBlock63,62,19);
        MazeBlock mazeBlock64 = new MazeBlock();
        addObject(mazeBlock64,59,19);
        MazeBlock mazeBlock65 = new MazeBlock();
        addObject(mazeBlock65,57,22);
        MazeBlock mazeBlock66 = new MazeBlock();
        addObject(mazeBlock66,57,25);
        MazeBlock mazeBlock67 = new MazeBlock();
        addObject(mazeBlock67,57,28);
        MazeBlock mazeBlock68 = new MazeBlock();
        addObject(mazeBlock68,32,34);
        MazeBlock mazeBlock69 = new MazeBlock();
        addObject(mazeBlock69,47,38);
        MazeBlock mazeBlock70 = new MazeBlock();
        addObject(mazeBlock70,1,1);
        MazeBlock mazeBlock71 = new MazeBlock();
        addObject(mazeBlock71,4,1);
        MazeBlock mazeBlock72 = new MazeBlock();
        addObject(mazeBlock72,7,1);
        MazeBlock mazeBlock73 = new MazeBlock();
        addObject(mazeBlock73,11,1);
        mazeBlock73.setLocation(11,2);
        mazeBlock73.setLocation(10,1);
        MazeBlock mazeBlock74 = new MazeBlock();
        addObject(mazeBlock74,1,8);
        MazeBlock mazeBlock75 = new MazeBlock();
        addObject(mazeBlock75,4,8);
        MazeBlock mazeBlock76 = new MazeBlock();
        addObject(mazeBlock76,3,11);
        mazeBlock76.setLocation(5,12);
        mazeBlock76.setLocation(4,11);
        MazeBlock mazeBlock77 = new MazeBlock();
        addObject(mazeBlock77,7,11);
        MazeBlock mazeBlock78 = new MazeBlock();
        addObject(mazeBlock78,10,11);
        MazeBlock mazeBlock79 = new MazeBlock();
        addObject(mazeBlock79,10,14);
        MazeBlock mazeBlock80 = new MazeBlock();
        addObject(mazeBlock80,10,18);
        mazeBlock80.setLocation(11,18);
        mazeBlock80.setLocation(10,17);
        MazeBlock mazeBlock81 = new MazeBlock();
        addObject(mazeBlock81,1,33);
        MazeBlock mazeBlock82 = new MazeBlock();
        addObject(mazeBlock82,4,33);
        MazeBlock mazeBlock83 = new MazeBlock();
        addObject(mazeBlock83,7,33);
        removeObject(mazeBlock81);
        removeObject(mazeBlock82);
        removeObject(mazeBlock83);
        MazeBlock MazeBlock81 = new MazeBlock();
        addObject(mazeBlock81,1,34);
        MazeBlock MazeBlock82 = new MazeBlock();
        addObject(mazeBlock82,4,34);
        MazeBlock MazeBlock83 = new MazeBlock();
        addObject(mazeBlock83,7,34);
        MazeBlock mazeBlock84 = new MazeBlock();
        addObject(mazeBlock84,10,34);
        removeObject(mazeBlock84);
        removeObject(mazeBlock83);
        removeObject(mazeBlock82);
        removeObject(mazeBlock81);
        MazeBlock azeBlock81 = new MazeBlock();
        addObject(mazeBlock81,7,38);
        MazeBlock azeBlock82 = new MazeBlock();
        addObject(mazeBlock82,1,32);
        MazeBlock azeBlock83 = new MazeBlock();
        addObject(mazeBlock83,4,32);
        MazeBlock MazeBlock84 = new MazeBlock();
        addObject(mazeBlock84,7,32);
        MazeBlock mazeBlock85 = new MazeBlock();
        addObject(mazeBlock85,11,32);
        mazeBlock85.setLocation(11,33);
        mazeBlock85.setLocation(10,33);
        mazeBlock85.setLocation(10,32);
        MazeBlock mazeBlock86 = new MazeBlock();
        addObject(mazeBlock86,1,35);
        MazeBlock mazeBlock87 = new MazeBlock();
        addObject(mazeBlock87,13,32);
        MazeBlock mazeBlock88 = new MazeBlock();
        addObject(mazeBlock88,13,29);
        MazeBlock mazeBlock89 = new MazeBlock();
        addObject(mazeBlock89,13,26);
        MazeBlock mazeBlock90 = new MazeBlock();
        addObject(mazeBlock90,20,4);
        MazeBlock mazeBlock91 = new MazeBlock();
        addObject(mazeBlock91,20,7);
        MazeBlock mazeBlock92 = new MazeBlock();
        addObject(mazeBlock92,17,7);
        MazeBlock mazeBlock93 = new MazeBlock();
        addObject(mazeBlock93,23,30);
        MazeBlock mazeBlock94 = new MazeBlock();
        addObject(mazeBlock94,13,17);
        MazeBlock mazeBlock95 = new MazeBlock();
        addObject(mazeBlock95,15,17);
        MazeBlock mazeBlock96 = new MazeBlock();
        addObject(mazeBlock96,10,26);
        MazeBlock mazeBlock97 = new MazeBlock();
        addObject(mazeBlock97,1,18);
        MazeBlock mazeBlock98 = new MazeBlock();
        addObject(mazeBlock98,4,29);
        MazeBlock mazeBlock99 = new MazeBlock();
        addObject(mazeBlock99,10,20);
        MazeBlock mazeBlock100 = new MazeBlock();
        addObject(mazeBlock100,23,27);
        MazeBlock mazeBlock101 = new MazeBlock();
        addObject(mazeBlock101,20,27);
        MazeBlock mazeBlock102 = new MazeBlock();
        addObject(mazeBlock102,23,33);
        MazeBlock mazeBlock103 = new MazeBlock();
        addObject(mazeBlock103,24,13);
        MazeBlock mazeBlock104 = new MazeBlock();
        addObject(mazeBlock104,23,36);
        MazeBlock mazeBlock105 = new MazeBlock();
        addObject(mazeBlock105,23,39);
        MazeBlock mazeBlock106 = new MazeBlock();
        addObject(mazeBlock106,57,31);
        MazeBlock mazeBlock107 = new MazeBlock();
        addObject(mazeBlock107,68,22);
        MazeBlock mazeBlock108 = new MazeBlock();
        addObject(mazeBlock108,60,25);
        MazeBlock mazeBlock109 = new MazeBlock();
        addObject(mazeBlock109,65,28);
        MazeBlock mazeBlock110 = new MazeBlock();
        addObject(mazeBlock110,55,38);
        mazeBlock110.setLocation(56,37);
        mazeBlock110.setLocation(56,38);
        mazeBlock110.setLocation(56,38);
        Gate gate = new Gate();
        addObject(gate,68,1);
        Key key = new Key();
        addObject(key,1,29);
        Spike spike = new Spike();
        addObject(spike,4,27);
        spike2 spike2 = new spike2();
        addObject(spike2,3,18);
        spike4 spike4 = new spike4();
        addObject(spike4,8,26);
        Spike spike3 = new Spike();
        addObject(spike3,7,9);
        spike2 spike22 = new spike2();
        addObject(spike22,15,26);
        spike3 spike32 = new spike3();
        addObject(spike32,10,3);
        removeObject(mazeBlock14);
        spike3 spike33 = new spike3();
        addObject(spike33,29,18);
        Spike spike5 = new Spike();
        addObject(spike5,29,20);
        Spike spike6 = new Spike();
        addObject(spike6,44,11);
        mazeBlock52.setLocation(39,2);
        Player player = new Player();
        addObject(player,61,22);
        mazeBlock109.setLocation(64,29);
        mazeBlock109.setLocation(65,31);
        mazeBlock52.setLocation(37,3);
        mazeBlock52.setLocation(38,4);
        mazeBlock.setLocation(52,38);
        mazeBlock.setLocation(53,38);
        removeObject(player);
        removeObject(mazeBlock65);
        mazeBlock66.setLocation(59,21);
        mazeBlock66.setLocation(60,22);
        mazeBlock66.setLocation(59,22);
        mazeBlock108.setLocation(60,24);
        mazeBlock108.setLocation(58,25);
        mazeBlock108.setLocation(59,26);
        mazeBlock108.setLocation(59,25);
        mazeBlock67.setLocation(62,30);
        mazeBlock67.setLocation(61,31);
        mazeBlock67.setLocation(60,31);
        mazeBlock67.setLocation(61,31);
        mazeBlock67.setLocation(62,31);
        mazeBlock106.setLocation(59,31);
        Player player2 = new Player();
        addObject(player2,68,38);
        removeObject(mazeBlock16);
        removeObject(mazeBlock17);
        removeObject(mazeBlock18);
        removeObject(mazeBlock19);
        removeObject(mazeBlock68);
        removeObject(mazeBlock20);
        removeObject(mazeBlock21);
        removeObject(mazeBlock22);
        removeObject(mazeBlock23);
        removeObject(mazeBlock24);
        removeObject(mazeBlock30);
        removeObject(mazeBlock31);
        removeObject(mazeBlock32);
        MazeBlock MazeBlock16 = new MazeBlock();
        addObject(mazeBlock16,47,25);
        MazeBlock MzeBlock17 = new MazeBlock();
        addObject(mazeBlock17,50,25);
        MazeBlock MazeBlock18 = new MazeBlock();
        addObject(mazeBlock18,32,31);
        MazeBlock MazeBlock19 = new MazeBlock();
        addObject(mazeBlock19,37,38);
        MazeBlock MazeBlock20 = new MazeBlock();
        addObject(mazeBlock20,40,38);
        MazeBlock MazeBlock21 = new MazeBlock();
        addObject(mazeBlock21,40,35);
        MazeBlock MazeBlock22 = new MazeBlock();
        addObject(mazeBlock22,40,32);
        Spike spike7 = new Spike();
        addObject(spike7,37,36);
        spike4 spike42 = new spike4();
        addObject(spike42,66,22);
        spike4 spike43 = new spike4();
        addObject(spike43,66,25);
        mazeBlock17.setLocation(50,24);
        mazeBlock18.setLocation(29,30);
        mazeBlock18.setLocation(32,31);
        mazeBlock18.setLocation(32,30);
        mazeBlock18.setLocation(32,31);
        removeObject(mazeBlock43);
        removeObject(mazeBlock41);
        removeObject(mazeBlock34);
        removeObject(mazeBlock40);
        removeObject(mazeBlock39);
        removeObject(mazeBlock37);
        mazeBlock28.setLocation(42,25);
        removeObject(mazeBlock27);
        removeObject(mazeBlock17);
        removeObject(mazeBlock33);
        removeObject(mazeBlock16);
        removeObject(mazeBlock29);
        mazeBlock18.setLocation(30,32);
        mazeBlock35.setLocation(49,29);
        mazeBlock35.setLocation(48,25);
        mazeBlock35.setLocation(48,27);
        mazeBlock35.setLocation(49,27);
        mazeBlock36.setLocation(49,23);
        mazeBlock36.setLocation(48,24);
        mazeBlock36.setLocation(50,24);
        mazeBlock36.setLocation(49,24);
        mazeBlock38.setLocation(46,23);
        mazeBlock38.setLocation(47,24);
        mazeBlock38.setLocation(46,24);
        mazeBlock28.setLocation(51,7);
        mazeBlock28.setLocation(50,7);
        mazeBlock42.setLocation(51,14);
        mazeBlock28.setLocation(50,11);
        mazeBlock28.setLocation(51,11);
        mazeBlock28.setLocation(51,11);
        mazeBlock105.setLocation(17,37);
        mazeBlock104.setLocation(18,34);
        mazeBlock102.setLocation(24,38);
        mazeBlock93.setLocation(25,36);
        mazeBlock93.setLocation(24,35);
        mazeBlock100.setLocation(25,32);
        mazeBlock100.setLocation(24,31);
        mazeBlock100.setLocation(24,32);
        mazeBlock101.setLocation(21,31);
        mazeBlock101.setLocation(21,32);
        mazeBlock101.setLocation(21,32);
        mazeBlock104.setLocation(18,33);
        removeObject(mazeBlock104);
        removeObject(mazeBlock105);
        spike2 spike23 = new spike2();
        addObject(spike23,32,32);
        spike2 spike24 = new spike2();
        addObject(spike24,31,22);
        mazeBlock26.setLocation(39,19);
        mazeBlock25.setLocation(34,27);
        mazeBlock26.setLocation(37,26);
        mazeBlock25.setLocation(33,26);
        mazeBlock25.setLocation(34,26);
        spike2 spike25 = new spike2();
        addObject(spike25,46,13);
        Spike spike8 = new Spike();
        addObject(spike8,49,22);
        mazeBlock69.setLocation(48,34);
        spike3 spike34 = new spike3();
        addObject(spike34,20,9);
        Spike spike9 = new Spike();
        addObject(spike9,24,30);
        MazeBlock mazeBlock111 = new MazeBlock();
        addObject(mazeBlock111,21,19);
        MazeBlock mazeBlock112 = new MazeBlock();
        addObject(mazeBlock112,21,22);
        spike4 spike44 = new spike4();
        addObject(spike44,19,22);
        mazeBlock112.setLocation(23,23);
        mazeBlock112.setLocation(23,23);
        mazeBlock112.setLocation(23,22);
        mazeBlock111.setLocation(23,19);
        mazeBlock111.setLocation(23,19);
        mazeBlock111.setLocation(22,19);
        mazeBlock112.setLocation(22,22);
        spike44.setLocation(19,22);
        spike44.setLocation(20,22);
        spike44.setLocation(19,22);
        spike44.setLocation(20,22);
        spike22.setLocation(15,29);
        mazeBlock91.setLocation(19,7);
        mazeBlock70.setLocation(1,1);
        mazeBlock70.setLocation(3,1);
        mazeBlock70.setLocation(1,1);
        mazeBlock70.setLocation(3,1);
        mazeBlock70.setLocation(5,1);
        mazeBlock70.setLocation(0,1);
        mazeBlock72.setLocation(2,1);
        mazeBlock71.setLocation(2,2);
        mazeBlock71.setLocation(8,1);
        mazeBlock72.setLocation(4,1);
        mazeBlock72.setLocation(4,0);
        mazeBlock70.setLocation(2,0);
        mazeBlock70.setLocation(7,1);
        removeObject(mazeBlock72);
        removeObject(mazeBlock71);
        addObject(mazeBlock71,4,1);
        addObject(mazeBlock72,1,1);
        mazeBlock71.setLocation(3,1);
        Timer timer = new Timer(60);
        addObject(timer,3,1);
        LuckyBox luckyBox = new LuckyBox();
        addObject(luckyBox,32,9);
        luckyBox.setLocation(32,9);
        mazeBlock71.setLocation(31,4);
        mazeBlock49.setLocation(4,1);
        mazeBlock71.setLocation(32,4);
        mazeBlock72.setLocation(31,4);
        mazeBlock71.setLocation(2,1);
        mazeBlock71.setLocation(1,2);
        mazeBlock71.setLocation(2,2);
        mazeBlock72.setLocation(32,4);
        mazeBlock49.setLocation(1,1);
        mazeBlock49.setLocation(4,2);
        mazeBlock49.setLocation(4,2);
        mazeBlock71.setLocation(1,2);
        mazeBlock49.setLocation(4,2);
        mazeBlock49.setLocation(4,2);
        mazeBlock71.setLocation(2,1);
        mazeBlock71.setLocation(1,2);
        mazeBlock49.setLocation(4,3);
        mazeBlock49.setLocation(4,3);
        mazeBlock49.setLocation(4,2);
        removeObject(mazeBlock49);
        removeObject(mazeBlock71);
        removeObject(mazeBlock70);
        timer.setLocation(4,8);
        mazeBlock75.setLocation(31,13);
        mazeBlock44.setLocation(4,8);
        mazeBlock75.setLocation(32,13);
    }
}
