import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class MazeWorld here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class MazeWorld extends World
{
    private Timer timer;
    
    public MazeWorld()
    {    
        // Create a new world with 600x400 cells with a cell size of 1x1 pixels.
        super(70, 40, 15); 
        blockPlacement();
        
        Player player = new Player();
        addObject(player,100,300);
        
        prepare();
        
        action();
    }

    private void blockPlacement(){
        MazeBlock mazeBlock = new MazeBlock();
        addObject(mazeBlock,54,18);
        MazeBlock mazeBlock2 = new MazeBlock();
        addObject(mazeBlock2,1,38);
        MazeBlock mazeBlock3 = new MazeBlock();
        addObject(mazeBlock3,1,35);
        MazeBlock mazeBlock4 = new MazeBlock();
        addObject(mazeBlock4,1,32);
        MazeBlock mazeBlock5 = new MazeBlock();
        addObject(mazeBlock5,1,29);
        MazeBlock mazeBlock6 = new MazeBlock();
        addObject(mazeBlock6,1,26);
        MazeBlock mazeBlock7 = new MazeBlock();
        addObject(mazeBlock7,1,22);
        MazeBlock mazeBlock8 = new MazeBlock();
        addObject(mazeBlock8,1,18);
        MazeBlock mazeBlock9 = new MazeBlock();
        addObject(mazeBlock9,2,13);
        removeObject(mazeBlock9);
        removeObject(mazeBlock);
        removeObject(mazeBlock8);
        removeObject(mazeBlock7);
        removeObject(mazeBlock6);
        removeObject(mazeBlock5);
        removeObject(mazeBlock4);
        removeObject(mazeBlock3);
        removeObject(mazeBlock2);
        addObject(mazeBlock,1,38);
        addObject(mazeBlock2,1,35);
        addObject(mazeBlock3,1,32);
        addObject(mazeBlock4,1,29);
        addObject(mazeBlock5,1,26);
        addObject(mazeBlock6,1,23);
        addObject(mazeBlock7,4,23);
        addObject(mazeBlock8,7,24);
        mazeBlock8.setLocation(8,24);
        removeObject(mazeBlock8);
        addObject(mazeBlock8,8,23);
        removeObject(mazeBlock8);
        addObject(mazeBlock8,7,23);
        addObject(mazeBlock9,9,38);
        removeObject(mazeBlock9);
        addObject(mazeBlock9,8,38);
        MazeBlock mazeBlock10 = new MazeBlock();
        addObject(mazeBlock10,8,35);
        MazeBlock mazeBlock11 = new MazeBlock();
        addObject(mazeBlock11,8,32);
        MazeBlock mazeBlock12 = new MazeBlock();
        addObject(mazeBlock12,8,28);
        removeObject(mazeBlock12);
        addObject(mazeBlock12,8,29);
        MazeBlock mazeBlock13 = new MazeBlock();
        addObject(mazeBlock13,11,29);
        MazeBlock mazeBlock14 = new MazeBlock();
        addObject(mazeBlock14,10,23);
        MazeBlock mazeBlock15 = new MazeBlock();
        addObject(mazeBlock15,27,38);
        MazeBlock mazeBlock16 = new MazeBlock();
        addObject(mazeBlock16,27,34);
        removeObject(mazeBlock16);
        addObject(mazeBlock16,27,35);
        MazeBlock mazeBlock17 = new MazeBlock();
        addObject(mazeBlock17,27,32);
        MazeBlock mazeBlock18 = new MazeBlock();
        addObject(mazeBlock18,27,29);
        MazeBlock mazeBlock19 = new MazeBlock();
        addObject(mazeBlock19,27,25);
        removeObject(mazeBlock19);
        addObject(mazeBlock19,27,26);
        MazeBlock mazeBlock20 = new MazeBlock();
        addObject(mazeBlock20,30,32);
        MazeBlock mazeBlock21 = new MazeBlock();
        addObject(mazeBlock21,33,32);
        MazeBlock mazeBlock22 = new MazeBlock();
        addObject(mazeBlock22,36,32);
        MazeBlock mazeBlock23 = new MazeBlock();
        addObject(mazeBlock23,31,1);
        MazeBlock mazeBlock24 = new MazeBlock();
        addObject(mazeBlock24,34,1);
        MazeBlock mazeBlock25 = new MazeBlock();
        addObject(mazeBlock25,34,4);
        MazeBlock mazeBlock26 = new MazeBlock();
        addObject(mazeBlock26,34,7);
        MazeBlock mazeBlock27 = new MazeBlock();
        addObject(mazeBlock27,14,15);
        MazeBlock mazeBlock28 = new MazeBlock();
        addObject(mazeBlock28,17,15);
        MazeBlock mazeBlock29 = new MazeBlock();
        addObject(mazeBlock29,20,15);
        MazeBlock mazeBlock30 = new MazeBlock();
        addObject(mazeBlock30,20,12);
        MazeBlock mazeBlock31 = new MazeBlock();
        addObject(mazeBlock31,20,9);
        removeObject(mazeBlock6);
        removeObject(mazeBlock5);
        removeObject(mazeBlock7);
        removeObject(mazeBlock12);
        removeObject(mazeBlock8);
        removeObject(mazeBlock14);
        removeObject(mazeBlock13);
        removeObject(mazeBlock4);
        mazeBlock10.setLocation(8,35);
        removeObject(mazeBlock11);
        removeObject(mazeBlock9);
        removeObject(mazeBlock10);
        removeObject(mazeBlock);
        removeObject(mazeBlock2);
        removeObject(mazeBlock3);
        addObject(mazeBlock,1,25);
        addObject(mazeBlock2,4,25);
        addObject(mazeBlock3,7,25);
        addObject(mazeBlock4,10,25);
        addObject(mazeBlock5,4,38);
        addObject(mazeBlock6,4,35);
        addObject(mazeBlock7,4,31);
        removeObject(mazeBlock7);
        addObject(mazeBlock7,4,32);
        addObject(mazeBlock8,7,35);
        addObject(mazeBlock9,10,35);
        removeObject(mazeBlock9);
        removeObject(mazeBlock8);
        addObject(mazeBlock8,45,38);
        addObject(mazeBlock9,45,35);
        addObject(mazeBlock10,45,32);
        addObject(mazeBlock11,45,29);
        addObject(mazeBlock12,45,25);
        removeObject(mazeBlock12);
        addObject(mazeBlock12,45,26);
        addObject(mazeBlock13,45,22);
        removeObject(mazeBlock13);
        addObject(mazeBlock13,45,23);
        addObject(mazeBlock14,45,20);
        MazeBlock mazeBlock32 = new MazeBlock();
        addObject(mazeBlock32,41,20);
        removeObject(mazeBlock32);
        addObject(mazeBlock32,41,20);
        removeObject(mazeBlock32);
        addObject(mazeBlock32,41,20);
        removeObject(mazeBlock32);
        addObject(mazeBlock32,42,20);
        MazeBlock mazeBlock33 = new MazeBlock();
        addObject(mazeBlock33,38,20);
        removeObject(mazeBlock33);
        addObject(mazeBlock33,38,20);
        removeObject(mazeBlock33);
        addObject(mazeBlock33,38,20);
        removeObject(mazeBlock33);
        addObject(mazeBlock33,39,20);
        MazeBlock mazeBlock34 = new MazeBlock();
        addObject(mazeBlock34,36,20);
        MazeBlock mazeBlock35 = new MazeBlock();
        addObject(mazeBlock35,30,35);
        MazeBlock mazeBlock36 = new MazeBlock();
        addObject(mazeBlock36,33,35);
        MazeBlock mazeBlock37 = new MazeBlock();
        addObject(mazeBlock37,36,35);
        removeObject(mazeBlock22);
        removeObject(mazeBlock21);
        removeObject(mazeBlock20);
        addObject(mazeBlock20,42,29);
        addObject(mazeBlock21,39,29);
        addObject(mazeBlock22,36,29);
        MazeBlock mazeBlock38 = new MazeBlock();
        addObject(mazeBlock38,39,35);
        removeObject(mazeBlock14);
        addObject(mazeBlock14,39,23);
        MazeBlock mazeBlock39 = new MazeBlock();
        addObject(mazeBlock39,42,23);
        MazeBlock mazeBlock40 = new MazeBlock();
        addObject(mazeBlock40,36,23);
        MazeBlock mazeBlock41 = new MazeBlock();
        addObject(mazeBlock41,33,23);
        MazeBlock mazeBlock42 = new MazeBlock();
        addObject(mazeBlock42,33,20);
        MazeBlock mazeBlock43 = new MazeBlock();
        addObject(mazeBlock43,30,22);
        removeObject(mazeBlock43);
        removeObject(mazeBlock42);
        removeObject(mazeBlock34);
        removeObject(mazeBlock33);
        addObject(mazeBlock33,33,29);
        removeObject(mazeBlock32);
        addObject(mazeBlock32,64,1);
        addObject(mazeBlock34,64,4);
        addObject(mazeBlock42,64,7);
        addObject(mazeBlock43,64,14);
        MazeBlock mazeBlock44 = new MazeBlock();
        addObject(mazeBlock44,67,14);
        removeObject(mazeBlock44);
        removeObject(mazeBlock43);
        addObject(mazeBlock43,68,14);
        addObject(mazeBlock44,64,14);
        removeObject(mazeBlock44);
        addObject(mazeBlock44,65,14);
        MazeBlock mazeBlock45 = new MazeBlock();
        addObject(mazeBlock45,62,14);
        MazeBlock mazeBlock46 = new MazeBlock();
        addObject(mazeBlock46,59,14);
        MazeBlock mazeBlock47 = new MazeBlock();
        addObject(mazeBlock47,56,14);
        MazeBlock mazeBlock48 = new MazeBlock();
        addObject(mazeBlock48,56,11);
        MazeBlock mazeBlock49 = new MazeBlock();
        addObject(mazeBlock49,56,7);
        removeObject(mazeBlock49);
        addObject(mazeBlock49,56,8);
        MazeBlock mazeBlock50 = new MazeBlock();
        addObject(mazeBlock50,56,5);
        removeObject(mazeBlock47);
        removeObject(mazeBlock13);
        addObject(mazeBlock13,57,23);
        addObject(mazeBlock47,57,26);
        MazeBlock mazeBlock51 = new MazeBlock();
        addObject(mazeBlock51,57,29);
        MazeBlock mazeBlock52 = new MazeBlock();
        addObject(mazeBlock52,57,32);
        MazeBlock mazeBlock53 = new MazeBlock();
        addObject(mazeBlock53,57,36);
        MazeBlock mazeBlock54 = new MazeBlock();
        addObject(mazeBlock54,57,39);
        mazeBlock52.setLocation(57,33);
        MazeBlock mazeBlock55 = new MazeBlock();
        addObject(mazeBlock55,57,33);
        MazeBlock mazeBlock56 = new MazeBlock();
        addObject(mazeBlock56,1,6);
        MazeBlock mazeBlock57 = new MazeBlock();
        addObject(mazeBlock57,4,6);
        MazeBlock mazeBlock58 = new MazeBlock();
        addObject(mazeBlock58,7,6);
        MazeBlock mazeBlock59 = new MazeBlock();
        addObject(mazeBlock59,10,6);
        MazeBlock mazeBlock60 = new MazeBlock();
        addObject(mazeBlock60,11,32);
        MazeBlock mazeBlock61 = new MazeBlock();
        addObject(mazeBlock61,14,32);
        MazeBlock mazeBlock62 = new MazeBlock();
        addObject(mazeBlock62,14,35);
        MazeBlock mazeBlock63 = new MazeBlock();
        addObject(mazeBlock63,24,29);
        MazeBlock mazeBlock64 = new MazeBlock();
        addObject(mazeBlock64,20,29);
        removeObject(mazeBlock64);
        addObject(mazeBlock64,21,29);
        MazeBlock mazeBlock65 = new MazeBlock();
        addObject(mazeBlock65,42,7);
        MazeBlock mazeBlock66 = new MazeBlock();
        addObject(mazeBlock66,42,10);
        MazeBlock mazeBlock67 = new MazeBlock();
        addObject(mazeBlock67,42,13);
        MazeBlock mazeBlock68 = new MazeBlock();
        addObject(mazeBlock68,45,13);
        MazeBlock mazeBlock69 = new MazeBlock();
        addObject(mazeBlock69,28,14);
        MazeBlock mazeBlock70 = new MazeBlock();
        addObject(mazeBlock70,31,14);
        MazeBlock mazeBlock71 = new MazeBlock();
        addObject(mazeBlock71,31,18);
        removeObject(mazeBlock71);
        addObject(mazeBlock71,31,18);
        removeObject(mazeBlock71);
        addObject(mazeBlock71,31,17);
        MazeBlock mazeBlock72 = new MazeBlock();
        addObject(mazeBlock72,16,21);
        MazeBlock mazeBlock73 = new MazeBlock();
        addObject(mazeBlock73,19,21);
        MazeBlock mazeBlock74 = new MazeBlock();
        addObject(mazeBlock74,22,21);
        MazeBlock mazeBlock75 = new MazeBlock();
        addObject(mazeBlock75,60,29);
        MazeBlock mazeBlock76 = new MazeBlock();
        addObject(mazeBlock76,63,29);
        MazeBlock mazeBlock77 = new MazeBlock();
        addObject(mazeBlock77,64,35);
        MazeBlock mazeBlock78 = new MazeBlock();
        addObject(mazeBlock78,68,35);
        mazeBlock78.setLocation(67,35);
        MazeBlock mazeBlock79 = new MazeBlock();
        addObject(mazeBlock79,67,35);
        MazeBlock mazeBlock80 = new MazeBlock();
        addObject(mazeBlock80,64,19);
        MazeBlock mazeBlock81 = new MazeBlock();
        addObject(mazeBlock81,64,22);
        MazeBlock mazeBlock82 = new MazeBlock();
        addObject(mazeBlock82,51,38);
        MazeBlock mazeBlock83 = new MazeBlock();
        addObject(mazeBlock83,51,35);
        MazeBlock mazeBlock84 = new MazeBlock();
        addObject(mazeBlock84,51,32);
        MazeBlock mazeBlock85 = new MazeBlock();
        addObject(mazeBlock85,51,29);
        MazeBlock mazeBlock86 = new MazeBlock();
        addObject(mazeBlock86,46,18);
        MazeBlock mazeBlock87 = new MazeBlock();
        addObject(mazeBlock87,49,18);
        removeObject(mazeBlock87);
        removeObject(mazeBlock86);
        addObject(mazeBlock86,52,19);
        addObject(mazeBlock87,49,19);
        MazeBlock mazeBlock88 = new MazeBlock();
        addObject(mazeBlock88,50,5);
        MazeBlock mazeBlock89 = new MazeBlock();
        addObject(mazeBlock89,53,5);
        MazeBlock mazeBlock90 = new MazeBlock();
        addObject(mazeBlock90,49,13);
        removeObject(mazeBlock90);
        addObject(mazeBlock90,48,13);
        MazeBlock mazeBlock91 = new MazeBlock();
        addObject(mazeBlock91,1,9);
        MazeBlock mazeBlock92 = new MazeBlock();
        addObject(mazeBlock92,1,12);
        MazeBlock mazeBlock93 = new MazeBlock();
        addObject(mazeBlock93,1,15);
        MazeBlock mazeBlock94 = new MazeBlock();
        addObject(mazeBlock94,16,1);
        MazeBlock mazeBlock95 = new MazeBlock();
        addObject(mazeBlock95,16,4);
        MazeBlock mazeBlock96 = new MazeBlock();
        addObject(mazeBlock96,7,15);
        MazeBlock mazeBlock97 = new MazeBlock();
        addObject(mazeBlock97,7,18);
        MazeBlock mazeBlock98 = new MazeBlock();
        addObject(mazeBlock98,24,38);
        removeObject(mazeBlock15);
        addObject(mazeBlock15,28,1);
        removeObject(mazeBlock48);
        addObject(mazeBlock48,57,11);
        removeObject(mazeBlock48);
        addObject(mazeBlock48,56,11);
        MazeBlock mazeBlock99 = new MazeBlock();
        addObject(mazeBlock99,37,17);
        MazeBlock mazeBlock100 = new MazeBlock();
        addObject(mazeBlock100,40,17);
        removeObject(mazeBlock67);
        removeObject(mazeBlock68);
        addObject(mazeBlock67,42,1);
        addObject(mazeBlock68,27,7);
        MazeBlock mazeBlock101 = new MazeBlock();
        addObject(mazeBlock101,27,38);
        removeObject(mazeBlock98);
        addObject(mazeBlock98,20,35);
        MazeBlock mazeBlock102 = new MazeBlock();
        addObject(mazeBlock102,20,38);
        MazeBlock mazeBlock103 = new MazeBlock();
        addObject(mazeBlock103,30,23);
        removeObject(mazeBlock39);
    }
    
    /**
     * Prepare the world for the start of the program.
     * That is: create the initial objects and add them to the world.
     */
    private void prepare()
    {

        MazeBlock mazeBlock = new MazeBlock();
        addObject(mazeBlock,24,24);
        MazeBlock mazeBlock2 = new MazeBlock();
        addObject(mazeBlock2,57,31);
        removeObject(mazeBlock);    
        addObject(mazeBlock,27,23);
        MazeBlock mazeBlock3 = new MazeBlock();
        addObject(mazeBlock3,24,23);
        MazeBlock mazeBlock4 = new MazeBlock();
        addObject(mazeBlock4,24,21);
        MazeBlock mazeBlock5 = new MazeBlock();
        addObject(mazeBlock5,54,23);
        mazeBlock5.setLocation(54,22);
        MazeBlock mazeBlock6 = new MazeBlock();
        addObject(mazeBlock6,54,22);
        mazeBlock6.setLocation(54,21);
        MazeBlock mazeBlock7 = new MazeBlock();
        addObject(mazeBlock7,54,21);
        MazeBlock mazeBlock8 = new MazeBlock();
        addObject(mazeBlock8,64,17);
        MazeBlock mazeBlock9 = new MazeBlock();
        addObject(mazeBlock9,20,6);
        MazeBlock mazeBlock10 = new MazeBlock();
        addObject(mazeBlock10,19,4);
        mazeBlock9.setLocation(20,6);
        MazeBlock mazeBlock11 = new MazeBlock();
        addObject(mazeBlock11,20,6);
        Key key = new Key();
        addObject(key,2,2);
        Gate gate = new Gate();
        addObject(gate,61,36);
        gate.setLocation(61,36);
        gate.setLocation(60,36);
        gate.setLocation(61,36);
        gate.setLocation(68,8);
        key.setLocation(1,2);

        Spike spike = new Spike();
        addObject(spike,45,24);
        spike2 spike2 = new spike2();
        addObject(spike2,41,23);
        Spike spike3 = new Spike();
        addObject(spike3,12,30);
        spike4 spike4 = new spike4();
        addObject(spike4,12,15);
        Spike spike5 = new Spike();
        addObject(spike5,48,11);
        spike2 spike22 = new spike2();
        addObject(spike22,50,13);
        spike4 spike42 = new spike4();
        addObject(spike42,46,13);
        Spike spike6 = new Spike();
        addObject(spike6,50,3);
        spike2 spike23 = new spike2();
        addObject(spike23,44,1);
        spike3 spike32 = new spike3();
        addObject(spike32,34,9);
        Spike spike7 = new Spike();
        addObject(spike7,10,23);
        Spike spike8 = new Spike();
        addObject(spike8,51,27);
        spike3 spike33 = new spike3();
        addObject(spike33,16,23);
        Spike spike9 = new Spike();
        addObject(spike9,4,30);
        Spike spike10 = new Spike();
        addObject(spike10,28,12);
        spike4 spike43 = new spike4();
        addObject(spike43,26,14);
        spike3 spike34 = new spike3();
        addObject(spike34,58,16);
        Spike spike11 = new Spike();
        addObject(spike11,24,19);
        spike2 spike24 = new spike2();
        addObject(spike24,22,35);
        removeObject(spike11);

        Timer timer = new Timer(60);
        addObject(timer,32,1);
        removeObject(spike2);
        removeObject(spike34);
        removeObject(spike22);
        LuckyBox luckyBox = new LuckyBox();
        addObject(luckyBox,30,38);
        luckyBox.setLocation(31,38);
        luckyBox.setLocation(60,33);
        luckyBox.setLocation(32,38);
        removeObject(luckyBox);
    }

    public void action(){  
    }
}